### ISSUE TITLE
python 3 issues.

### ISSUE THREAD

**Issue by eprifti** [TeamErlich/dna-fountain#1]
Hello,
First of all thanks for this great project. I was trying it out and I have the following configuration:
- Python 3.6.0 |Anaconda 4.3.0 (x86_64)| (default, Dec 23 2016, 13:19:00)

After compilation and building, I can not run encode.py. The following error occurs:

```
python dna-fountain/encode.py --file_in info_to_code.tar.gz --size 32 -m 3 --gc 0.05 --rs 2 --delta 0.001 --c_dist 0.025 --out info_to_code.tar.gz.dna --stop 72000
Traceback (most recent call last):
  File "dna-fountain/encode.py", line 9, in <module>
    from fountain import DNAFountain
  File "fountain.pyx", line 5, in init fountain (fountain.c:3663)
    from droplet import Droplet
  File "droplet.pyx", line 5, in init droplet (droplet.c:2294)
    from utils import int_to_four, four_to_dna
  File "utils.pyx", line 5, in init utils (utils.c:10448)
    from string import maketrans   # Required to call maketrans function.
ImportError: cannot import name maketrans
```
It looks like maketrans and python 3 are not going along well together (http://stackoverflow.com/questions/27539884/maketrans-not-working-for-petl-with-python3-4/27540139)

Could you propose any workarounds?

Thanks
Edi

**Comment by erlichya** [comment]
Hi Edi,

Thanks for letting us know. We tested the code with Python 2. Can you simply switch to this version?

**Comment by merkys** [comment]
[Python 2 is reaching its end-of-life in 2020](https://legacy.python.org/dev/peps/pep-0373/), so it's better to switch to Python 3.

**Comment by HrishiDhondge** [comment]
For the moment, the addition of a file for all requirements would be useful to create a virtual environment using conda or pip.

[requirements.txt](https://github.com/TeamErlich/dna-fountain/files/5695691/requirements.txt)

**Comment by jdbrody** [comment]
A couple of students at Franklin and Marshall College have ported the code to Python3.  I've done some basic testing and it seems to work:
https://github.com/jdbrody/dna-fountain
